name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.2.0=py37_0
  - attrs=19.3.0=py_0
  - boost-cpp=1.70.0=h8e57a91_2
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h8022711_0
  - cfitsio=3.470=hb60a0a2_2
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py_0
  - conda=4.7.12=py37_0
  - conda-package-handling=1.6.0=py37h516909a_1
  - cryptography=2.8=py37h72c5cf5_1
  - curl=7.65.3=hf8cf82a_0
  - expat=2.2.5=he1b5a44_1004
  - fiona=1.8.11=py37h900e953_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - freexl=1.0.5=h14c3975_1002
  - gdal=3.0.2=py37hbb6b9fb_5
  - geopandas=0.6.0=py_0
  - geos=3.8.0=he1b5a44_0
  - geotiff=1.5.1=hbd99317_7
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.1.7=h516909a_1
  - glib=2.58.3=py37h6f030ca_1002
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - idna=2.8=py37_1000
  - jpeg=9c=h14c3975_1001
  - json-c=0.13.1=h14c3975_1001
  - kealib=1.4.10=h58c409b_1005
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.65.3=hda55be3_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=hdf63c60_0
  - libgdal=3.0.2=h30a29e3_5
  - libgfortran-ng=7.3.0=hdf63c60_2
  - libiconv=1.15=h516909a_1005
  - libkml=1.3.0=h4fcabce_1010
  - liblapack=3.8.0=14_openblas
  - libnetcdf=4.7.1=nompi_h94020b1_102
  - libopenblas=0.3.7=h5ec1e0e_4
  - libpng=1.6.37=hed695b0_0
  - libpq=11.5=hd9ab2ff_2
  - libspatialindex=1.9.3=he1b5a44_1
  - libspatialite=4.3.0a=h343d7df_1033
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_1
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=hf4e8a37_4
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - munch=2.5.0=py_0
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.17.3=py37h95a1406_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1d=h516909a_0
  - pandas=0.25.3=py37hb3f55d8_0
  - pcre=8.43=he1b5a44_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - poppler=0.67.0=h14e79db_8
  - poppler-data=0.4.9=1
  - postgresql=11.5=hc63931a_2
  - proj=6.2.1=hc80f0dc_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycosat=0.6.3=py37h516909a_1002
  - pycparser=2.19=py37_1
  - pyopenssl=19.1.0=py37_0
  - pyproj=2.4.2.post1=py37h12732c1_0
  - pysocks=1.7.1=py37_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - rtree=0.9.1=py37h7b0cdae_0
  - ruamel_yaml=0.15.80=py37h516909a_1000
  - setuptools=42.0.2=py37_0
  - shapely=1.6.4=py37h5d51c17_1007
  - six=1.13.0=py37_0
  - sqlite=3.30.1=hcee41ef_0
  - tbb=2018.0.5=h2d50403_0
  - tiledb=1.7.0=hcde45ca_2
  - tk=8.6.10=hed695b0_0
  - tqdm=4.40.0=py_0
  - tzcode=2019a=h516909a_1002
  - urllib3=1.25.7=py37_0
  - wheel=0.33.6=py37_0
  - xerces-c=3.2.2=h8412b87_1004
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
prefix: /opt/conda

